### ISSUE TITLE
[Feature] Add support to alfa3 country code

### ISSUE THREAD

**Issue by fvisticot** [cedvdb/flutter_circle_flags#1]
Would be nice to add this feature
alfa3 codes: https://datahelpdesk.worldbank.org/knowledgebase/articles/898590-country-api-queries

In attach a json file with alfa2 / alfa3 from previous website

[countries.json.zip](https://github.com/cedvdb/flutter_circle_flags/files/6561056/countries.json.zip)

**Comment by cedvdb** [comment]
I mean, this should be pretty easy to add but I think the conversion should be done by the user outside the library.
