### ISSUE TITLE
Flags not updated from current gallery

### ISSUE THREAD

**Issue by WillyTrek19** [cedvdb/flutter_circle_flags#12]
I tried to add a flag using
```
CircleFlag('es-ct')
```
and it says that it is not found in the database/repository.

Looking into your assets, I found that there are many flags that haven't been uploaded from the gallery. Could you upload them?

**Comment by cedvdb** [comment]
@WillyTrek19  Here is the original library: https://github.com/HatScripts/circle-flags to use to add new flags.

Could you add them ?

**Comment by WillyTrek19** [comment]
I would, but I don't have permission to push any changes into this repository. If you give it to me I could do it right now.

**Comment by cedvdb** [comment]
You have the permission to make a PR
